### PR TITLE
Bbl changes - clean up parameters, namespace, gitignore

### PR DESCRIPTION
**Pull request by bpbond**
See #6

### CODE REVIEW

**Comment by kaizadp** [comment]
Thanks, @bpbond! 

Two questions/comments:

1. why are we gitignoring the .md files?
2. you deleted `lock.cache=T` in my `make(plan)` command. I've got the `cache locked, cannot make plan` error multiple times. Do you have a way around that?

**Comment by bpbond** [comment]
1. Your .Rmd file transformed by `rmarkdown` to an .md file and then to .html; we want the first of those version-tracked, but not the others, as they're automatically generated from your Rmd file.

2. Hmm. I've never seen that error. Were you trying to invoke the plan from within a debug session perhaps? Otherwise I'm confused.

**Comment by kaizadp** [comment]
2. No, I was running the plan from a regular session. I think `drake` just doesn't like me. Anyway, the `lock.cache=F` is my workaround for now.

1. But if I change the material inside the .rmd, that won't be reflected in the .md unless I commit it, correct? Like if I add a new graph or new text.
- same with gitignoring the figures. The .md file uses the .png files stored on GitHub. So if we don't update the figures, we're still displaying the old versions.

**Comment by bpbond** [comment]
3. That's correct, and in general, that's how version control should work: we commit our 'source' files but not our 'products'. We commit source code, not the resulting software; commit Rmd, not html.

**Pull request merged**
